account_field_mapping = {'CompanyName': 'Zoom_Company_Name__c',
                       'City': 'Zoom_City__c',
                       'TopLevelIndustry': 'Zoom_Industry_Label__c',
                       'Industry': 'Zoom_Secondary_industry_label__c',
                       'Phone': 'Zoom_Company_phone_number__c',
                       'State': 'Zoom_State__c',
                       'Street': 'Zoom_Street_address__c',
                       'Employees': 'Zoom_Headcount__c',
                       'AlexaRanking': 'Zoom_Alexa_Rank__c',
                         'Zip': 'Zoom_Zip__c',
                         'CountryCode': 'Zoom_Company_Country__c',
                         'CompanyID': 'Zoom_company_ID__c',
                         'Website': 'Zoom_Website__c',
                         'RevenueIn000s': 'Zoom_Revenue_in_000s__c',
                         }


contact_field_mapping = {'PersonID': 'Zoom_Individual_ID__c',
                            'LastName': 'Zoom_Last_name__c',
                            'FirstName': 'Zoom_First_name__c',
                            'JobTitle': 'Zoom_Job_title__c',
                            'DirectPhone': 'Zoom_Direct_Phone_Number__c',
                            'Email': 'Zoom_Email_address__c',
                            'Street': 'Zoom_Person_Street__c',
                            'City': 'Zoom_Person_City__c',
                            'State': 'Zoom_Person_State__c',
                            'Zip': 'Zoom_Person_Zip__c',
                            'CountryCode': 'Zoom_Country__c',
                            'LastUpdatedDate': 'Zoom_Last_updated_date__c',
                            }